//all types of actions here

//Profile actions
export const FETCH_PROFILE_REQUEST = "FETCH_PROFILE_REQUEST"
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS"
export const FETCH_PROFILE_FAILURE = "FETCH_PROFILE_FAILURE"

//Auth actions
export const FETCH_AUTH_REQUEST = "FETCH_AUTH_REQUEST"
export const FETCH_AUTH_SUCCESS = "FETCH_AUTH_SUCCESS"
export const FETCH_AUTH_FAILURE = "FETCH_AUTH_FAILURE"
export const DELETE_AUTH_TOKEN = "DELETE_AUTH_TOKEN"

//Plan actions
export const FETCH_PLAN_REQUEST = "FETCH_PLAN_REQUEST"
export const FETCH_PLAN_SUCCESS = "FETCH_PLAN_SUCCESS"
export const FETCH_PLAN_FAILURE = "FETCH_PLAN_FAILURE"

//Actions for getting new employees
export const FETCH_PLAN_EMPLOYEES_REQUEST = "FETCH_PLAN_EMPLOYEES_REQUEST"
export const FETCH_PLAN_EMPLOYEES_SUCCESS = "FETCH_PLAN_EMPLOYEES_SUCCESS"
export const FETCH_PLAN_EMPLOYEES_FAILURE = "FETCH_PLAN_EMPLOYEES_FAILURE"

//News actions


//Notifications actions