//all types of actions here

//Profile actions
export const FETCH_PROFILE_REQUEST = "FETCH_PROFILE_REQUEST"
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS"
export const FETCH_PROFILE_FAILURE = "FETCH_PROFILE_FAILURE"

//Auth actions
export const FETCH_AUTH_REQUEST = "FETCH_AUTH_REQUEST"
export const FETCH_AUTH_SUCCESS = "FETCH_AUTH_SUCCESS"
export const FETCH_AUTH_FAILURE = "FETCH_AUTH_FAILURE"
export const DELETE_AUTH_TOKEN = "DELETE_AUTH_TOKEN"

//Plan actions
export const FETCH_PLAN_REQUEST = "FETCH_PLAN_REQUEST"
export const FETCH_PLAN_SUCCESS = "FETCH_PLAN_SUCCESS"
export const FETCH_PLAN_FAILURE = "FETCH_PLAN_FAILURE"
export const FETCH_BEGIN_PLAN = "FETCH_BEGIN_PLAN"
export const FETCH_UPDATE_LEADER = "FETCH_UPDATE_LEADER"
export const FETCH_UPDATE_HREMPLOYEE = "FETCH_UPDATE_HREMPLOYEE"
export const FETCH_UPDATE_RATING = "FETCH_UPDATE_RATING"
export const FETCH_UPDATE_ADAPTATION_START = "FETCH_UPDATE_ADAPTATION_START"
export const FETCH_UPDATE_ADAPTATION_END = "FETCH_UPDATE_ADAPTATION_END"
export const FETCH_ADD_TASK = "FETCH_ADD_TASK"
export const FETCH_DELETE_TASK = "FETCH_DELETE_TASK"

//Actions for new employees
export const FETCH_PLAN_EMPLOYEES_REQUEST = "FETCH_PLAN_EMPLOYEES_REQUEST"
export const FETCH_PLAN_EMPLOYEES_SUCCESS = "FETCH_PLAN_EMPLOYEES_SUCCESS"
export const FETCH_PLAN_EMPLOYEES_FAILURE = "FETCH_PLAN_EMPLOYEES_FAILURE"
export const FETCH_PLAN_HREMPLOYEES = "FETCH_PLAN_HREMPLOYEES"
export const FETCH_PLAN_LEADERS = "FETCH_PLAN_LEADERS"

//News actions


//Notifications actions